// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoEgpCTpd7juw4z_7eezD6eJR5hKEHEIw',
    appId: '1:132363977917:web:6834a82a3de766ecdd23d4',
    messagingSenderId: '132363977917',
    projectId: 'test-flutter-9981e',
    authDomain: 'test-flutter-9981e.firebaseapp.com',
    databaseURL: 'https://test-flutter-9981e-default-rtdb.firebaseio.com',
    storageBucket: 'test-flutter-9981e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLjcAm89RIz5EBcERK5KrI2Y4wbwC0OA',
    appId: '1:132363977917:android:2b48651f98d4933ddd23d4',
    messagingSenderId: '132363977917',
    projectId: 'test-flutter-9981e',
    databaseURL: 'https://test-flutter-9981e-default-rtdb.firebaseio.com',
    storageBucket: 'test-flutter-9981e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAexhsDu3Sq8zJUxHjgegDNIqnEw6zqNxU',
    appId: '1:132363977917:web:963b739c78d48c9ddd23d4',
    messagingSenderId: '132363977917',
    projectId: 'test-flutter-9981e',
    authDomain: 'test-flutter-9981e.firebaseapp.com',
    databaseURL: 'https://test-flutter-9981e-default-rtdb.firebaseio.com',
    storageBucket: 'test-flutter-9981e.firebasestorage.app',
  );
}
